#!/stage1/busybox sh
_PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

load_image=/stage1/boot.cpio
extra_image=/mnt/efs/boot.cpio.gz

if busybox grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	load_image=/stage1/recovery.cpio
	extra_image=/mnt/efs/recovery.cpio.gz
fi

busybox cpio -i < ${load_image}

busybox mount -t ext4 /dev/block/mmcblk0p7 /mnt/efs

# install lvm files and apply overlay if it exists
if busybox test -f /stage1/lvm.cpio ; then
	busybox cpio -i < /stage1/lvm.cpio
fi

# apply ramdisk overlay from /efs partition
if busybox test -f ${extra_image} ; then
	busybox zcat ${extra_image} | busybox cpio -i -u
fi
if busybox test -f /mnt/efs/lvm.cpio.gz ; then
	busybox zcat /mnt/efs/lvm.cpio.gz | busybox cpio -i -u
fi

busybox test -f /mnt/efs/extra.sh && busybox sh /mnt/efs/extra.sh
busybox umount /mnt/efs

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
